ALTER TABLE BCA_CLIENTVENDOR 
ADD COLUMN isMobilePhoneNumber BOOLEAN;
ALTER TABLE BCA_CLIENTVENDOR ADD COLUMN isPhoneMobileNumber BOOLEAN;

UPDATE BCA_CLIENTVENDOR SET isMobilePhoneNumber=FALSE;
UPDATE BCA_CLIENTVENDOR SET isPhoneMobileNumber=TRUE;
