ALTER TABLE BCA_CLIENTVENDOR 
ADD COLUMN isMobilePhoneNumber BOOLEAN;
ALTER TABLE BCA_CLIENTVENDOR ADD COLUMN isPhoneMobileNumber BOOLEAN;

UPDATE BCA_CLIENTVENDOR SET isMobilePhoneNumber=FALSE;
UPDATE BCA_CLIENTVENDOR SET isPhoneMobileNumber=TRUE;

 SET SESSION sql_mode='NO_AUTO_VALUE_ON_ZERO';
ALTER TABLE `bzc`.`bca_cvcategory`   
  CHANGE `CVCategoryID` `CVCategoryID` INT(11) NOT NULL AUTO_INCREMENT,
  CHANGE `CompanyID` `CompanyID` INT(11) NULL, 
  ADD PRIMARY KEY (`CVCategoryID`);
