package com.avibha.common.constants;


import com.avibha.common.Resource;

public class AppConstants {

	public static String InvoiceType = "InvoiceType";
	public static String EstType = "EstType";
	public static String SOType = "SOType";
	public static String POType = "POType";

	/** all states in the U.S. */
	public static final String state_cb[] = { "", Resource.get("AK"),
			Resource.get("AL"), Resource.get("AR"), Resource.get("AZ"),
			Resource.get("CA"), Resource.get("CO"), Resource.get("CT"),
			Resource.get("DC"), Resource.get("DE"), Resource.get("FL"),
			Resource.get("GA"), Resource.get("HI"), Resource.get("IA"),
			Resource.get("ID"), Resource.get("IL"), Resource.get("IN"),
			Resource.get("KS"), Resource.get("KY"), Resource.get("MA"),
			Resource.get("MD"), Resource.get("ME"), Resource.get("MI"),
			Resource.get("MN"), Resource.get("MO"), Resource.get("MS"),
			Resource.get("MT"), Resource.get("NC"), Resource.get("ND"),
			Resource.get("NE"), Resource.get("NH"), Resource.get("NJ"),
			Resource.get("NM"), Resource.get("NV"), Resource.get("NY"),
			Resource.get("OH"), Resource.get("OK"), Resource.get("OR"),
			Resource.get("PA"), Resource.get("RI"), Resource.get("SC"),
			Resource.get("SD"), Resource.get("TN"), Resource.get("TX"),
			Resource.get("UT"), Resource.get("VA"), Resource.get("VT"),
			Resource.get("WA"), Resource.get("WI"), Resource.get("WV"),
			Resource.get("WY") };
	/** countries */
	public static final String country_cb[] = { "", Resource.get("Albania"),
			Resource.get("Algeria"), Resource.get("American_Samoa"),
			Resource.get("Andorra"), Resource.get("Angola"),
			Resource.get("Anguilla"), Resource.get("Antigua"),
			Resource.get("Argentina"), Resource.get("Armenia"),
			Resource.get("Aruba"), Resource.get("Australia"),
			Resource.get("Austria"), Resource.get("Azerbaijan"),
			Resource.get("Bahamas"), Resource.get("Bangladesh"),
			Resource.get("Barbados"), Resource.get("Barbuda"),
			Resource.get("Belarus"), Resource.get("Belgium"),
			Resource.get("Benin"), Resource.get("Bermuda"),
			Resource.get("Bhutan"), Resource.get("Bolivia"),
			Resource.get("Bonaire"), Resource.get("Botswana"),
			Resource.get("Brazil"), Resource.get("British_Virgin_Island"),
			Resource.get("Brunei"), Resource.get("Bulgaria"),
			Resource.get("Burkina_Faso"), Resource.get("Burundi"),
			Resource.get("Cambodia"), Resource.get("Cameroon"),
			Resource.get("Canada"), Resource.get("Cape_Verde"),
			Resource.get("Cayman_Islands"),
			Resource.get("Central_African_Republic"), Resource.get("Chad"),
			Resource.get("Channel_Islands_(U.K.)"), Resource.get("Chile"),
			Resource.get("China"), Resource.get("Colombia"),
			Resource.get("Congo"), Resource.get("Cook_Islands"),
			Resource.get("Corsica"), Resource.get("Croatia"),
			Resource.get("Curacao"), Resource.get("Cyprus"),
			Resource.get("Czeck_Republic"), Resource.get("Denmark"),
			Resource.get("Djibouti"), Resource.get("Dominica"),
			Resource.get("Dominican_Republic"), Resource.get("Ecuador"),
			Resource.get("Egypt"), Resource.get("El_Salvador"),
			Resource.get("England_(U.K.)"), Resource.get("Equatorial_Guinea"),
			Resource.get("Eritrea"), Resource.get("Estonia"),
			Resource.get("Ethiopia"), Resource.get("Faroe_Island"),
			Resource.get("Fiji"), Resource.get("Finland"),
			Resource.get("France"), Resource.get("French_Guiana"),
			Resource.get("French_Polyn."), Resource.get("Gabon"),
			Resource.get("Gambia"), Resource.get("Georgia"),
			Resource.get("Germany"), Resource.get("Ghana"),
			Resource.get("Gibraltar"), Resource.get("Greece"),
			Resource.get("Greenland"), Resource.get("Grenada"),
			Resource.get("Guadeloupe"), Resource.get("Guam"),
			Resource.get("Guatemala"), Resource.get("Guinea"),
			Resource.get("Guinea-Bissau"), Resource.get("Guyana"),
			Resource.get("Haiti"), Resource.get("Honduras"),
			Resource.get("Hong_Kong"), Resource.get("Hungary"),
			Resource.get("Iceland"), Resource.get("India"),
			Resource.get("Indonesia"), Resource.get("Ireland"),
			Resource.get("Israel"), Resource.get("Italy"),
			Resource.get("Ivory_Coast"), Resource.get("Jamaica"),
			Resource.get("Japan"), Resource.get("Jordan"),
			Resource.get("Kazakhstan"), Resource.get("Kenya"),
			Resource.get("Korea,_South"), Resource.get("Kuwait"),
			Resource.get("Kyrgyzstan"), Resource.get("Latvia"),
			Resource.get("Lebanon"), Resource.get("Lesotho"),
			Resource.get("Liechtenstein"), Resource.get("Lithuania"),
			Resource.get("Luxembourg"), Resource.get("Macau"),
			Resource.get("Macedonia"), Resource.get("Madagascar"),
			Resource.get("Malawi"), Resource.get("Malaysia"),
			Resource.get("Maldives,_Repuglic_of"), Resource.get("Mali"),
			Resource.get("Malta"), Resource.get("Marshall_Islands"),
			Resource.get("Martinique"), Resource.get("Mauritania"),
			Resource.get("Mauritius"), Resource.get("Mexico"),
			Resource.get("Micronesia"), Resource.get("Moldova"),
			Resource.get("Monaco"), Resource.get("Mongolia"),
			Resource.get("Montserrat"), Resource.get("Morocco"),
			Resource.get("Mozambique"), Resource.get("Myanmar"),
			Resource.get("Namibia"), Resource.get("Nepal"),
			Resource.get("Netherlands_(Holland)"),
			Resource.get("Netherlands_Antilles"),
			Resource.get("New_Caledonia"), Resource.get("New_Zealand"),
			Resource.get("Nicaragua"), Resource.get("Niger"),
			Resource.get("Nigeria"), Resource.get("Norway"),
			Resource.get("Oman"), Resource.get("Pakistan"),
			Resource.get("Palau"), Resource.get("Panama"),
			Resource.get("Papua_New_Guinea"), Resource.get("Paraguay"),
			Resource.get("Peru"), Resource.get("Philippines"),
			Resource.get("Poland"), Resource.get("Portugal"),
			Resource.get("Qatar"), Resource.get("Reunion_Island"),
			Resource.get("Romania"), Resource.get("Russia"),
			Resource.get("Rwanda"), Resource.get("Saba"),
			Resource.get("St._Barthelemy"), Resource.get("St._Croix"),
			Resource.get("St._Eustatius"), Resource.get("St._John"),
			Resource.get("St._Kitts_and_Nevis"), Resource.get("St._Lucia"),
			Resource.get("St._Maarten/St._Martin"), Resource.get("St._Thomas"),
			Resource.get("St._Vincent"), Resource.get("Saipan"),
			Resource.get("San_Marino"), Resource.get("Saudi_Arabia"),
			Resource.get("Scotland_(U.K.)"), Resource.get("Senegal"),
			Resource.get("Seychelles"), Resource.get("Sierra_Leone"),
			Resource.get("Singapore"), Resource.get("Slovak_Republic"),
			Resource.get("Slovenia"), Resource.get("Somalia"),
			Resource.get("South_Africa"), Resource.get("Spain"),
			Resource.get("Sri_Lanka"), Resource.get("Sudan"),
			Resource.get("Suriname"), Resource.get("Swaziland"),
			Resource.get("Switzerland"), Resource.get("Syria"),
			Resource.get("Taiwan"), Resource.get("Tanzania"),
			Resource.get("Thailand"), Resource.get("Togo"),
			Resource.get("Trinidad_and_Tobago"), Resource.get("Tunisia"),
			Resource.get("Turkey"), Resource.get("Turkmenistan"),
			Resource.get("Turks_and_Caicos_Island"), Resource.get("Uganda"),
			Resource.get("Ukraine"), Resource.get("United_Arab_Emirates"),
			Resource.get("United_States"), Resource.get("Uruguay"),
			Resource.get("U.S._Virgin_Islands"), Resource.get("Uzbekistan"),
			Resource.get("Vanuatu"), Resource.get("Vatican_City"),
			Resource.get("Venezuela"), Resource.get("Vietnam"),
			Resource.get("Wales_(U.K.)"), Resource.get("Wallis_and_Futuna"),
			Resource.get("Yemen_Arab_Repblic"), Resource.get("Zaire"),
			Resource.get("Zambia"), Resource.get("Zimbabwe") };

}
